background {
    monitor =
    path = ~/Pictures/wallpapers/wallhaven-jev965.jpg
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
}

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H')"
    color = rgba(255, 255, 255, 0.9)
    font_size = 110
    font_family = JetBrainsMono Nerd Font
    position = 0, 220
    halign = center
    valign = center
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%M')"
    color = rgba(255, 255, 255, 0.9)
    font_size = 110
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

# Day
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %b')"
    color = rgba(255, 255, 255, 0.4)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -10
    halign = center
    valign = center
}

# Input
input-field {
    monitor =
    size = 280, 44
    outline_thickness = 1
    outer_color = rgba(255, 255, 255, 0.08)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgba(255, 255, 255, 0.6)
    placeholder_text = <i>password</i>
    fade_on_empty = true
    rounding = 4
    position = 0, 100
    halign = center
    valign = bottom
}
